apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: shoprupee

rules:

  # Deployments
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  # Services
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  # Secrets - required for private ECR
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  # Pods - required for verification
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer
  namespace: shoprupee

subjects:

  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: shoprupee

roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io
